language: php

sudo: required
dist: precise

php:
  - 7.0
  - 7.1
  - nightly

git:
  depth: 1

cache:
  apt: true
  ccache: true
  timeout: 691200
  directories:
    - .temp
    #- vendor
    - $HOME/.ccache
    - $HOME/.composer/cache

services:
  - mongodb
  - memcached
  - redis-server
  - postgresql

env:
  global:
    - TEST_BT_HOST="127.0.0.1"
    - TEST_BT_PORT="11300"
    - TEST_MC_HOST="127.0.0.1"
    - TEST_MC_PORT="11211"
    - TEST_DB_MYSQL_HOST="127.0.0.1"
    - TEST_DB_MYSQL_PORT="3306"
    - TEST_DB_MYSQL_USER="root"
    - TEST_DB_MYSQL_PASSWD=""
    - TEST_DB_MYSQL_NAME="phalcon_test"
    - TEST_DB_MYSQL_CHARSET="utf8"
    - TEST_DB_MYSQL_DSN="mysql:host=127.0.0.1;dbname=phalcon_test"
    - TEST_DB_MONGO_HOST="127.0.0.1"
    - TEST_DB_MONGO_PORT="27017"
    - TEST_DB_MONGO_USER="admin"
    - TEST_DB_MONGO_PASSWD=""
    - TEST_DB_MONGO_NAME="phalcon_test"
    - TEST_RS_HOST="127.0.0.1"
    - TEST_RS_PORT="6379"
    - ZEND_DONT_UNLOAD_MODULES=1
    - CC="ccache gcc"

before_install:
  - export PATH=$PATH:~/bin;
  - composer self-update -q
  - travis_retry composer --prefer-source install
  - ./unit-tests/ci/install_prereqs.sh
  - ./unit-tests/ci/setup_dbs.sh

before_script:
  - git submodule --quiet update --init --recursive
  - (cd ext; export CFLAGS="-g -O0 -std=gnu90 -Wall -Werror -Wno-error=uninitialized"; phpize && ./configure --silent --enable-phalcon && make --silent -j4 > /dev/null && make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini)
  - ulimit -c unlimited -S || true
  - echo '/tmp/core_%e.%p' | sudo tee /proc/sys/kernel/core_pattern &> /dev/null

script:
  - vendor/bin/phpunit --debug unit-tests/

after_failure:
  - bash unit-tests/ci/after_failure.sh

notifications:
  email:
    - dreamsxin@qq.com

addons:
  apt:
    packages:
      - gdb
      - re2c
      - libpng12-dev
